### ISSUE TITLE
epoch index calculation can fail

### ISSUE THREAD

**Issue by alessandrofelder** [SilverLabUCL/PySilverLabNWB#16]
in pynwb's `epoch.py` idx and count are calculated from the start_time and end_time arguments that we pass to silverlabs nwbFile.add_epoch here: https://github.com/SilverLabUCL/PySilverLabNWB/blob/608507a98747bff46d667e8893e800aeb07a103b/src/silverlabnwb/nwb_file.py#L494-L498

This happens in trial0007. idx should be 70360 according to reset times, but gets assigned to 70359.

The reason for this is that by subtracting the "intra-trial" time from timestamp at index 70360 we land on a time just before the timestamp at 70359. The difference is ~1e-14, so may be linked to changes in precision,

**Comment by alessandrofelder** [comment]
The file that we tested is , which is [not tested on Travis](https://travis-ci.org/SilverLabUCL/PySilverLabNWB/jobs/610469846?utm_medium=notification&utm_source=github_status) so (probably) we wouldn't have noticed this in the signature comparison earlier.

**Comment by alessandrofelder** [comment]
Changing line to https://github.com/SilverLabUCL/PySilverLabNWB/blob/608507a98747bff46d667e8893e800aeb07a103b/src/silverlabnwb/nwb_file.py#L482 to `epoch_times[:, 0] -= (trial_times[reset_idxs[:, 0]]-1) * 1e-6` seems to correct this. Could this be accounting for the way we count cycles between the start of the trial and the first measurement? See changes made in [this commit](https://github.com/SilverLabUCL/AnalysisPipeline/commit/3a510e60c5616c07ea614cd57e5daf511186e3bd)!

**Comment by jonc125** [comment]
I think we resolved this?

**Comment by alessandrofelder** [comment]
Indeed, we did. Fixed in https://github.com/SilverLabUCL/PySilverLabNWB/commit/bb7bbdbb28d47fb036185ed45e3ab489967c6cba.
