### ISSUE TITLE
Dummy metadata copied into file

### ISSUE THREAD

**Issue by ageorgou** [SilverLabUCL/PySilverLabNWB#37]
Some fields of `metadata.yaml` are pre-populated with values describing what their actual content should be (e.g. "A general description of the experiment goes here."). This is useful for people filling them in but, if someone doesn't, these dummy values are copied into the NWB file. 

Consider not including them unless they are filled in, except for any fields which are required for creating the `NWBFile`.

**Comment by pgleeson** [comment]
I would suggest just commenting out the lines in metadata.yaml which provide the hints for contents and ignoring these when reading it in. Then users can see clearly what they have and haven't filled in yet.

**Comment by jonc125** [comment]
For the GUI editor, would be good to have a template file or similar with those notes available to be read, so they can be provided as hint tooltips for the user.

**Comment by ageorgou** [comment]
We may be able to get away with a single YAML file for both uses if we switch to `ruamel.yaml` instead of `pyyaml` for reading `metadata.yaml`. The former doesn't discard the comments, so they could be used to populate the GUI. See [this answer](https://stackoverflow.com/questions/38252507/how-can-i-get-comments-from-a-yaml-file-using-ruamel-yaml-in-python) for how to access the comments.

**Comment by jonc125** [comment]
Good idea!

**Comment by alessandrofelder** [comment]
I think this is taken care of by #45. Please re-open if I am mistaken.
