### ISSUE TITLE
Improve signature creation for NWB2 files

### ISSUE THREAD

**Issue by jonc125** [SilverLabUCL/PySilverLabNWB#8]
Follow-up from https://github.com/SilverLabUCL/AnalysisPipeline/pull/43, https://github.com/SilverLabUCL/AnalysisPipeline/pull/44 etc.

Should no longer need to worry about Python 2 support. Also I think trying to convert signatures from NWB1 to NWB2 is getting too difficult. Let's just make sure we can get a consistent signature for NWB2 files, and manually test the first data load, as I did initially with NWB1.

**Comment by ageorgou** [comment]
Done in #22, cleaned up a bit more in #43.
